INSERT INTO PRODUCTOS VALUES(1, 'Crema facial', 20, 300);
INSERT INTO PRODUCTOS VALUES(2, 'Crema corporal', 20, 20);
INSERT INTO PRODUCTOS VALUES(3, 'Bloqueador', 30, 100);
INSERT INTO PRODUCTOS VALUES(4, 'Locion tonica', 15, 70);
INSERT INTO PRODUCTOS VALUES(5, 'Desmaquillante', 30, 25);
INSERT INTO PRODUCTOS VALUES(6, 'Jabon', 5, 200);
INSERT INTO PRODUCTOS VALUES(7, 'Espuma limpiadora', 30, 50);
INSERT INTO PRODUCTOS VALUES(8, 'Exfoliante', 20, 15);
INSERT INTO PRODUCTOS VALUES(9, 'Talco', 13, 120);
INSERT INTO PRODUCTOS VALUES(10, 'Colonia', 7, 80);
INSERT INTO PRODUCTOS VALUES(11, 'Crema labial', 11, 85);
INSERT INTO PRODUCTOS VALUES(12, 'Alcohol gel', 20, 20);
INSERT INTO PRODUCTOS VALUES(13, 'Quitaesmalte', 10, 150);
INSERT INTO PRODUCTOS VALUES(14, 'Repelente', 15, 10);
INSERT INTO PRODUCTOS VALUES(15, 'Aceite almendras', 5, 100);

SELECT * FROM PRODUCTOS;